{% set name = "EQcorrscan" %}
{% set version = "0.5.0" %}
{% set sha256 = "bf36e0d6eccb5257bfceeaa8c40b744d8519978e49330835d73d5fd5fbed73c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
      fn: {{ name }}-{{ version }}.tar.gz
      url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
      sha256: {{ sha256 }}
#     fn: 0.5.0rc0.tar.gz
#     url: https://github.com/eqcorrscan/EQcorrscan/archive/0.5.0rc0.tar.gz

build:
  skip: true  # [win and py==38]
  number: 0


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - future
    - numpy
    - fftw
    - llvm-openmp >=4.0.1  # [osx]
  run:
    - python
    - setuptools
    - future
    - {{ pin_compatible('numpy') }}
    - fftw
    - scipy
    - matplotlib-base
    - obspy
    - bottleneck
    - pyproj
    - h5py
    - llvm-openmp >=4.0.1  # [osx]

about:
  home: http://eqcorrscan.readthedocs.io/
  license: LGPL-3.0-or-later
  license_file: LICENCE.txt
  summary: Detection and analysis of repeating and near-repeating earthquakes
  description: |
    EQcorrscan is a Python package for detection and analysis of repeating
    and near-repeating earthquakes.
  doc_url: http://eqcorrscan.readthedocs.io/
  dev_url: https://github.com/eqcorrscan/eqcorrscan

extra:
  recipe-maintainers:
    - calum-chamberlain
