travis:
  secure:
    BINSTAR_TOKEN: T8ToSqgL8cYA2lL/LhdQ6c9RWtKiaibrsDdtWY3qViVjhQ7vSjHgzSXWpOD7QUbo/py4imv0AuDvbteBOYgjt21Env6ZGvRTXNwxR5nL2PJSHgJfQr5yOs5vSMO016Wo0zkXFacE/q+UytG/FHumvtYh4RVVEln3pf0SEO7O3+U7eB+2rUrSJbHvofwQ8e0qykxcp3AVRCepTzR1g/NRnzEBcelId+Wn799+4q+0H66nMXAxz8/QetMvAYsLCsHwySw0E1I8I4fMpXl+fD6A2Rb4EG2OFjycw2MpoCp3YT9Zu+xVFdrc0O2Cp6W6UM3hjFdabvRfqGdIrPxRv9cgc3jzp+SBF5RqPtV8gOhVG8sJpPUBWhicPT2lMr1PeHcdZC9H5dQsrjD0myWMlXjTdoyqiljdM+qD5Z4xNnrU7rkXGQFU+O4qxP1GqSSCEQlu9kA6ZF/K+WW2uHGo8UrSs64Nw7YKaEfJ4t0kOqXE36y6fkqetrJX5plu3YpDQMGHuACFq/oIiTwT961bhcktlV34ec60K+luBhsQHnZDS/E68HsT0pAWXwT1RgwvMRFJt0DCb0O1PRzdo+lXfyMk5P2O0cVJcjxOYOtZUvc9D4DlZsvJAEekT2zCP+SmW0wMRi6X6YAQz/d1aCiINGS7ztvcz8mhzIOouugQjGfPZFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
